name: Download Artifacts
run-name: ${{ github.run_id }}
on: workflow_dispatch
jobs:
  download_and_cat:
    name: Download and cat artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_PAT }}
          run-id: ${{ secrets.ARTIFACTS_RUN_ID }}
          path: dist
          merge-multiple: true
      - run: |
          ls -la
          cat dist/test.txt
          cat dist/test2.txt
