name: Download Artifacts
run-name: ${{ github.run_id }}
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        type: string
jobs:
  download_and_cat:
    name: Download and cat artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
      - run: |
          ls -la
