name: Upload Artifacts
run-name: ${{ github.run_id }}
on: push
jobs:
  artifact_1:
    name: Upload artifact 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello_1 > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: art1
          path: test.txt
  artifact_2:
    name: Upload artifact 2
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello_2 > test2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: art2
          path: test2.txt
  run_id_secret:
    name: Create/Update ARTIFACTS_RUN_ID secret
    runs-on: ubuntu-latest
    needs: [artifact_1, artifact_2]
    steps:
      - run: |
          gh secret set ARTIFACTS_RUN_ID --body ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}
